<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?PHP
$A=5;
    $B=$A++;
    echo $B;
    $a=5;
    $b=6;
    $c=$a+$b;
    echo'the addition is'.$
    $A=100;
    $B=200;
    IF($A==10 || $B==200){
        ECHO"TRUE";
    }
ELSE{ 
    echo"FALSE";
}
    ?>
</body>
</html>